### ISSUE TITLE
Request for transfer: power-assert-js organization

### ISSUE THREAD

**Issue by twada** [azu/espower-babel#14]
Hi @azu, I've created new organization [power-assert-js](https://github.com/power-assert-js) to help users to find related products easily, and I want you to transfer this project to power-assert-js org.

If you agree with me, please see [Transferring a repository](https://help.github.com/articles/transferring-a-repository/) for details. If you do not want to transfer, it's no problem at all ;)

Thanks!
(And sorry for creating same issue with intelli-espower-loader)

**Comment by azu** [comment]
power-assert-js/espower-babel/ :runner:

**Comment by twada** [comment]
@azu Thanks!!!
